# fly.toml app configuration file generated for glossary-bot on 2023-09-07T08:53:33-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "glossary-bot"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
