name: Deploy

on:
  push:
    branches:
      - develop
      - stable
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false

jobs:
  dev:
    concurrency: hg-sandbox
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy-to-fly.yaml
    secrets:
      fly_access_token: ${{ secrets.FLY_API_TOKEN }}
      gloss_bot_slack_token: ${{ secrets.GLOSS_BOT_SLACK_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      app_name: hg-ops-glossarybot-develop
      environment: 'hg-sandbox'

  stable:
    concurrency: Hypergiant
    if: github.ref == 'refs/heads/stable'
    uses: ./.github/workflows/deploy-to-fly.yaml
    secrets:
      fly_access_token: ${{ secrets.FLY_API_TOKEN }}
      gloss_bot_slack_token: ${{ secrets.GLOSS_BOT_SLACK_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      app_name: hg-ops-glossarybot-stable
      environment: 'Hypergiant'
