name: Deploy

on:
  push:
    branches:
      - develop
      - stable
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: false

jobs:
  set-fly-app-name:
    uses: ./.github/workflows/set-fly-app-name.yaml
    with:
      ref: ${{ inputs.branch || github.head_ref || github.ref }} # Use the input if it's there, otherwise use the head ref, otherwise use the ref

  dev:
    concurrency: hg-sandbox
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/deploy-to-fly.yaml
    secrets:
      fly_access_token: ${{ secrets.FLY_API_TOKEN }}
    with:
      app_name: glossary-bot-develop
      environment: 'hg-sandbox'

  stable:
    concurrency: Hypergiant
    if: github.ref == 'refs/heads/stable'
    uses: ./.github/workflows/deploy-to-fly.yaml
    secrets:
      fly_access_token: ${{ secrets.FLY_API_TOKEN }}
    with:
      app_name: glossary-bot-stable
      environment: 'Hypergiant'